ELearning/ELearning/Models/StoryViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Models
{ 
    public class StoryViewModel
    {
        public IPagedList<StoryModel> Stories { get; set; }

    } 

    public class StoryModel
    {
        public int ID { get; set; } = 0;
        public string Title { get; set; } = "";

        [AllowHtml]
        public string Content { get; set; } = "";
        public int ClassID { get; set; } = 0;
        public string ClassName { get; set; } = "";
        public int AddedBy { get; set; } = 0;
        public DateTime DateAdded { get; set; } = new DateTime();
        public int UpdatedBy { get; set; } = 0;
        public DateTime DateUpdated { get; set; } = new DateTime();
        public int DeletedBy { get; set; } = 0;
        public DateTime DateDeleted { get; set; } = new DateTime();
        public bool IsDeleted { get; set; } = false;
        public int CheckedBy { get; set; } = 0;
        public string AddedByName { get; set; } = "";
        public int QuizAttempt { get; set; } = 0;
        public bool AllowToRetake { get; set; } = false;
        public int[] SelectedSectionIds { get; set; }
        public int[] SelectedStudentIds { get; set; }

        public IEnumerable<SelectListItem> ClassList { get; set; }
        public List<PageContent> PageContents { get; set; } = new List<PageContent>();

        public StudentProgressModel Progress { get; set; }
    }

    public class PageContent
    {
        public int PageNumber { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }

    public class StoryFileUploadViewModel
    {
        public HttpPostedFileBase File { get; set; }
        public int ClassID { get; set; } = 0;
        public int[] SelectedSectionIds { get; set; }
        public int[] SelectedStudentIds { get; set; }
        public IEnumerable<SelectListItem> ClassList { get; set; }
    }

    public class QuestionViewModel
    {
        public int StoryID { get; set; } = 0;
        public string StoryTitle { get; set; } = "";
        public IPagedList<QuestionModel> Questions { get; set; }

    }

    public class QuestionStudentViewModel
    {
        public int StoryID { get; set; } = 0;
        public string StoryTitle { get; set; } = "";
        public List<QuestionModel> Questions { get; set; }

    }

    public class QuestionModel
    {
        public int ID { get; set; } = 0;

        [AllowHtml]
        public string Question { get; set; } = "";
        public int StoryID { get; set; } = 0;
        public int AddedBy { get; set; } = 0;
        public DateTime DateAdded { get; set; } = new DateTime();
        public int UpdatedBy { get; set; } = 0;
        public DateTime DateUpdated { get; set; } = new DateTime();
        public int DeletedBy { get; set; } = 0;
        public DateTime DateDeleted { get; set; } = new DateTime();
        public bool IsDeleted { get; set; } = false; 
    }

    public class AnswerModel
    {
        public int ID { get; set; } = 0;
        public int QuestionID { get; set; } = 0;
        public string Option { get; set; } = "";
        public bool IsCorrect { get; set; } = false;
        public int Sequence { get; set; } = 0;
    }

    public class QuestionAndAnswerModel
    {
        public int StoryID { get; set; } = 0;
        public string Question { get; set; } = "";
        public string Option1 { get; set; } = "";
        public string Option2 { get; set; } = "";
        public string Option3 { get; set; } = "";
        public string Option4 { get; set; } = "";
        public int CorrectAnswer { get; set; } = 0;
    }

    public class QuestionResultModel
    {
        public int QuestionID { get; set; } = 0;
        public int AnswerID { get; set; } = 0; 
    }

    public class QuestionResultViewModel
    {
        public int StoryID { get; set; } = 0; 
        public int StudentID { get; set; } = 0;
        public List<QuestionResultModel> QuestionResults { get; set; }
    }

    public class GradeModel
    {
        public int StudentID { get; set; } = 0; 
        public int StoryID { get; set; } = 0;
        public int QuestionID { get; set; } = 0;
        public int StudentAnswerID { get; set; } = 0;
        public int Attempt { get; set; } = 0;
    }

    public class QuizAssessmentModel
    {
        public decimal QuizAssessmentPercentage { get; set; } = 0;
        public string QuizAssessmentIcon { get; set; } = "";
        public string QuizAssessmentMessage { get; set; } = "";
    }

    public class AnswerComputeModel
    {
        public int CountCorrectAnswer { get; set; } = 0;
        public int CountTotalQuestion { get; set; } = 0;
    }

    public class StudentSubmissionModel
    {
        public string StoryTitle { get; set; } = "";
        public string StudentName { get; set; } = "";
        public decimal ResultPercentage { get; set; } = 0;
    }

    public class QuestionStudentAnswerViewModel
    {
        public int StoryID { get; set; } = 0;
        public int StudentID { get; set; } = 0; 
        public List<QuestionStudentAnswerModel> QuestionResults { get; set; }
    }

    public class QuestionStudentAnswerModel
    {
        public int QuestionID { get; set; } = 0;
        public string Answer { get; set; } = "";
    }

    public class QuizHistoryViewModel
    {
        public IPagedList<StoryModel> Stories { get; set; }
    }

    public class QuizGradeByStudentViewModel
    {
        public string StoryTitle { get; set; } = "";
        public List<QuizGradeByStudentModel> QuizGradeList { get; set; }
    }

    public class QuizGradeByStudentModel
    {
        public int ID { get; set; } = 0;
        public int StudentID { get; set; } = 0;
        public int StoryID { get; set; } = 0;
        public string StoryTitle { get; set; } = "";
        public int Attempt { get; set; } = 0;
        public int TotalQuestions { get; set; } = 0;
        public int Grade { get; set; } = 0;
        public decimal GradePercentage { get; set; } = 0;
        public string Remarks { get; set; } = "";
        public string CheckedBy { get; set; } = "";
        public DateTime DateChecked { get; set; } = new DateTime();
    }

    public class DetailedQuizGradeByStudentViewModel
    { 
        public List<DetailedQuizGradeByStudentModel> QuizGradeDetailedList { get; set; }
    }

    public class DetailedQuizGradeByStudentModel
    {
        public int QuestionID { get; set; } = 0;
        public string StoryQuestion { get; set; } = "";
        public string StudentAnswer { get; set; } = "";
        public int Score { get; set; } = 0;
        public DateTime DateAnswered { get; set; } = new DateTime();
        public int StudentID { get; set; } = 0;
        public int StoryID { get; set; } = 0;
        public string StoryTitle { get; set; } = "";
        public int Attempt { get; set; } = 0;
        public int TotalQuestions { get; set; } = 0;
        public int Grade { get; set; } = 0;
        public decimal GradePercentage { get; set; } = 0;
        public string Remarks { get; set; } = "";
        public string CheckedBy { get; set; } = "";
        public DateTime DateChecked { get; set; } = new DateTime();
    }

    public class StudentProgressModel
    {
        public int ID { get; set; } = 0;
        public int StudentID { get; set; } = 0;
        public int StoryID { get; set; } = 0;
        public int LastPageRead { get; set; } = 0;
        public int TotalPages { get; set; } = 0;
        public string Status { get; set; } = "";
        public int StoryCategoryID { get; set; } = 0;
    }

    public class StoryCategoryModel
    {
        public int ID { get; set; } = 0; 
        public string Code { get; set; } = "";
        public string Name { get; set; } = "";
        public int Sequence { get; set; } = 0;
    }

}

ELearning/ELearning/Controllers/StoryController.cs
using ELearning.Models;
using MySql.Data.MySqlClient;
using NAudio.Lame;
using NAudio.Wave;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Speech.AudioFormat;
using System.Linq;
using System.Speech.Synthesis;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions; 
using PagedList;

namespace ELearning.Controllers
{
    public class StoryController : Controller
    {
        private string usertype = "student";
        string defaultConnection = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
        // GET: Story
        public ActionResult Index()
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login) 
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }
             
            List<StoryCategoryModel> list = new List<StoryCategoryModel>();
            list = GetStoryCategories();
             

            return View(list);
        }

        public ActionResult Category(int? id)
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login) 
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            if(id == null)
            {
                return HttpNotFound();
            }

            int classID = (int)Session["ClassID"];
            int studentID = (int)Session["UserID"];
            int sectionID = (int)Session["SectionID"];
            List<StoryModel> list = new List<StoryModel>();
            list = GetAllStoriesByStudent(id.Value, classID, studentID);

            if (list.Count == 0)
                GetAllStoriesBySection(id.Value, classID, sectionID, studentID);

            return View(list);
        }

        public ActionResult Detail(int? id)
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login)
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var studentid = (int)Session["UserID"];
            StoryModel model = GetStoryByIDDB(id.Value, studentid);

            return View(model);
        } 

        public ActionResult Question(int? id)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            StoryModel course = GetStoriesByID(id.Value);
            QuestionStudentViewModel model = new QuestionStudentViewModel();
            model.Questions = GetQuestionsByStoryID(id.Value);
            model.StoryID = id.Value;
            model.StoryTitle = course.Title;

            return View(model);
        }
         
        [HttpPost]
        public JsonResult QuizSubmission(QuestionStudentAnswerViewModel model)
        {
            ResultModel resultModel = new ResultModel();
            DateTime datenow = DateTime.Now;
            int count = 0;
             
            if(model.QuestionResults != null && model.QuestionResults.Count > 0)
            {
                var attempt = GetStudentAnswerAttemptByStory(model.StudentID, model.StoryID);
                foreach (var qr in model.QuestionResults)
                { 
                    count += AddStudentAnswerDB(qr.QuestionID, model.StudentID, qr.Answer, datenow, (attempt + 1));
                }

                if(count > 0)
                {
                    StudentProgressFalseRetake(model.StoryID, model.StudentID);
                    resultModel.success = true;
                    resultModel.message = "Answers successfully submitted. Please wait for your teacher to check.";
                }
                else
                {
                    resultModel.success = false;
                    resultModel.message = "Failed to submit answers. Please check again.";
                }
            }
            else
            {
                resultModel.success = false;
                resultModel.message = "Failed to submit answers. Please check again.";
            }

            return Json(resultModel);
        }

        public JsonResult ViewQuizResult(int storyid)
        { 
            QuizAssessmentModel resultModel = new QuizAssessmentModel();
            AnswerComputeModel model = new AnswerComputeModel();
            var studentid = (int)Session["UserID"];
            model = GetQuizAssessmentDB(studentid, storyid, 1);

            if (model != null)
            {
                resultModel.QuizAssessmentPercentage = (int)Math.Round(((decimal)model.CountCorrectAnswer / model.CountTotalQuestion) * 100);

                if (resultModel.QuizAssessmentPercentage >= 60)
                {
                    resultModel.QuizAssessmentIcon = "success";
                    resultModel.QuizAssessmentMessage = "Nice job, you passed!";
                }
                else
                {
                    resultModel.QuizAssessmentIcon = "error";
                    resultModel.QuizAssessmentMessage = "Sorry, you didn't pass.";
                }
            }
            else
            {
                resultModel.QuizAssessmentPercentage = 0;
                resultModel.QuizAssessmentIcon = "info";
                resultModel.QuizAssessmentMessage = "There was an error when retrieving your quiz result.";
            }


            return Json(resultModel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult QuizHistory(int? page)
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login)
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            var studentid = (int)Session["UserID"];
            var stories = GetStoryByStudentDB(studentid);

            QuizHistoryViewModel model = new QuizHistoryViewModel();
            model.Stories = stories.ToPagedList(pageNumber, pageSize); 

            return View(model);
        }
        public ActionResult QuizHistoryAttempt(int? id)
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login)
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var studentid = (int)Session["UserID"];
            var list = GetQuizResultByStoryDB(studentid, id.Value);

            QuizGradeByStudentViewModel model = new QuizGradeByStudentViewModel();
            model.QuizGradeList = list;
            model.StoryTitle = list != null && list.Count > 0 ? list.Select(l => l.StoryTitle).FirstOrDefault() : "";

            return View(model);
        }
        public ActionResult QuizHistoryAttemptDetail(int? id, int? attempt)
        {
            if (Session["UserName"] == null)
            {
                // Store the current URL (for redirecting after login)
                return RedirectToAction("Login", "Account", new { returnUrl = Request.Url.AbsoluteUri });
            }

            if (id == null)
            {
                return HttpNotFound();
            }

            var studentid = (int)Session["UserID"];
            var list = GetDetailedQuizResultByStoryDB(studentid, id.Value, attempt.Value);

            DetailedQuizGradeByStudentViewModel model = new DetailedQuizGradeByStudentViewModel();
            model.QuizGradeDetailedList = list; 

            return View(model);
        }

        [HttpPost]
        public JsonResult SaveProgress(int StoryID, int StudentID, int LastPageRead, int TotalPages)
        {
            try
            {
                StudentProgressModel model = new StudentProgressModel();
                model.StoryID = StoryID;
                model.StudentID = StudentID;
                model.TotalPages = TotalPages;

                var progress = GetStudentProgress(StudentID, StoryID);
                if (progress == null)
                {
                    // If no progress entry exists, create a new one 
                    model.LastPageRead = LastPageRead;
                    model.Status = LastPageRead == -1 ? "Not Started" : "In Progress";
                }
                else
                {
                    // If entry exists, update the LastPageRead and Status 
                    model.LastPageRead = LastPageRead;
                    model.Status = (LastPageRead == -1) ? "Not Started" :
                                      (LastPageRead == progress.TotalPages ? "Completed" : "In Progress");
                }

                // Save changes to the database 
                UpdateStudentProgress(model);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }



        private List<StoryCategoryModel> GetStoryCategories()
        {
            List<StoryCategoryModel> list = new List<StoryCategoryModel>();
            MySqlConnection con = new MySqlConnection(defaultConnection);
            MySqlCommand cmd = con.CreateCommand(); 

ELearning/ELearning/Views/Story/Category.cshtml
@model List<ELearning.Models.StoryModel>
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    ViewBag.Title = "Stories"; //ViewBag.CategoryTitle;

    var categoryid = ViewContext.RouteData.Values["id"] != null ? Convert.ToInt32(ViewContext.RouteData.Values["id"].ToString()) : 0;
}

<!-- Page Title -->
<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>@ViewBag.Title</h1>
                </div>
            </div>
        </div>
    </div>
</div><!-- End Page Title -->
<!-- Stories Section -->
<section id="courses" class="courses section">

    <div class="container">

        <div class="row">

            @if (Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 d-flex align-items-stretch mb-3">
                        <div class="course-item">
                            <div class="course-content">
                                @Html.Hidden($"QuizAttempt[{item.ID}]", item.QuizAttempt)
                                @Html.Hidden($"AllowToRetake[{item.ID}]", item.AllowToRetake ? "true" : "false")
                                <h3>
                                    @*@if (categoryid == 3)
                                    {
                                        if (item.QuizAttempt > 0 && !item.AllowToRetake)
                                        {
                                            <a href="@Url.Action("QuizHistoryAttempt", "Story", new { id = item.ID })">@item.Title</a>
                                        }
                                        else if (item.QuizAttempt == 0 && !item.AllowToRetake)
                                        {
                                            <a href="@Url.Action("Question", "Story", new { id = item.ID })">@item.Title</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Detail", "Story", new { id = item.ID })">@item.Title</a>
                                        }
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Detail", "Story", new { id = item.ID })">@item.Title</a>
                                    }*@

                                    @if (categoryid == 3)
                                    {
                                        if (item.QuizAttempt > 0 && !item.AllowToRetake)
                                        {
                                            <a href="@Url.Action("QuizHistoryAttempt", "Story", new { id = item.ID })">@item.Title</a>
                                        }
                                        else 
                                        {
                                            <a href="@Url.Action("Question", "Story", new { id = item.ID })">@item.Title</a>
                                        } 
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Detail", "Story", new { id = item.ID })">@item.Title</a>
                                    }
                                </h3>
                                <div class="description" id="course_@item.ID">@Html.Raw(item.Content)</div>
                                <div class="trainer d-flex justify-content-between align-items-center">
                                    <div class="trainer-profile d-flex align-items-center">
                                        @*<img src="assets/img/trainers/trainer-1-2.jpg" class="img-fluid" alt="">*@
                                        <a href="javascript:void(0)" class="trainer-link">By: @item.AddedByName</a>
                                    </div>
                                    <div class="trainer-rank d-flex align-items-center"> 
                                        @if (categoryid == 3)
                                        {
                                            if (item.QuizAttempt > 0 && !item.AllowToRetake)
                                            {
                                                <a href="@Url.Action("QuizHistoryAttempt", "Story", new { id = item.ID })">
                                                     <small>@Html.Raw((item.QuizAttempt > 0 && item.CheckedBy > 0) ? "Pending" : "View Quiz Result")</small>
                                                </a>
                                            } 
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- End Story Item-->
                }
            }
            else
            {
                <p>No Stories under this category</p>
            }

        </div>

    </div>

</section><!-- /Stories Section -->

@section Scripts { 
    <script>
        $(document).ready(function () {
            var elements = document.querySelectorAll(`.description`);
            elements.forEach(element => {
                var storyid = element.id.replace('course_', '');
                var quizattempt = document.getElementById(`QuizAttempt_${storyid}_`).value;
                var allowtoretake = document.getElementById(`AllowToRetake_${storyid}_`).value;
                var categoryid = @categoryid;
                if (element.innerText.length > 100) {
                    //element.innerHTML = element.innerText.slice(0, 100) + `... <a href="/Story/${(categoryid == 3 ? (parseInt(quizattempt) > 0 && allowtoretake == "false" ? "QuizHistoryAttempt" : (parseInt(quizattempt) == 0 && allowtoretake == "false" ? "Question" : "Detail")) : "Detail")}/${storyid}">read more</a>`;
                    element.innerHTML = element.innerText.slice(0, 100) + `... <a href="/Story/${(categoryid == 3 ? (parseInt(quizattempt) > 0 && allowtoretake == "false" ? "QuizHistoryAttempt" : "Question") : "Detail")}/${storyid}">read more</a>`;
                }
            });
        });
    </script>
}

ELearning/ELearning/Views/Story/Detail - Copy.cshtml
@model ELearning.Models.StoryModel
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    ViewBag.Title = "Stories";
}

@section Styles {
    <style>
        .highlight {
            background-color: yellow;
        }

        #stopButton {
            display: none;
        }

        .flipbook {
            width: 50%;
            height: 50rem;
            position: relative;
            margin: 20px auto;
            perspective: 1000px;
        }

        /* Title Page (Cover) */
        .fb-cover {
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            background: #eee;
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 5;
            border: 1px solid #ddd;
            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);
            transition: opacity 0.6s ease;
        }

            .fb-cover.hidden {
                opacity: 0;
                z-index: -1;
            }

        .fb-title-content {
            color: white;
            font-size: 32px;
            text-transform: uppercase;
        }

        .fb-page {
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            background: white;
            border: 1px solid #ddd;
            backface-visibility: hidden;
            transform-origin: left;
            transition: transform 0.6s ease;
            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);
            z-index: 1;
        }

            .fb-page.flipped {
                transform: rotateY(-180deg);
                z-index: 0;
            }

        .fb-content {
            padding: 20px; /* Adjust padding if needed */
            height: 100%;
            position: relative;
        }

        .fb-page-title {
            position: absolute; /* Position the small element absolutely within the page */
            bottom: 10px; /* Distance from the bottom */
            right: 10px; /* Distance from the right */
            font-size: 12px; /* Adjust the font size */
            color: #666; /* Adjust the color as per your theme */
            font-style: italic; /* Optional styling */
        }

        .fb-readable-word {
            cursor: pointer; /* Makes the word look clickable */
            color: blue; /* Optional styling to differentiate clickable words */
            text-decoration: underline;
        }

            .fb-readable-word:hover {
                color: darkblue; /* Change color on hover */
            }
    </style>

}

<!-- Page Title -->
<div class="page-title" data-aos="fade">
    <div class="heading">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-8">
                    <h1>@ViewBag.Title</h1>
                </div>
            </div>
        </div>
    </div>
</div><!-- End Page Title -->
<!-- Stories Story Details Section -->
<section id="stories-story-details" class="stories-story-details section">
    <div class="flipbook">
        <!-- Title Page (Cover) -->
        <div class="fb-cover">
            <div class="fb-title-content">
                <h1>@Model.Title</h1>
            </div>
        </div>

        <!-- Dynamic Flipbook Pages -->
        @foreach (var page in Model.PageContents)
        {
            <div class="fb-page">
                <div class="fb-content">
                    @*<p class="fb-page-content">@Html.Raw(page.Content)</p>*@
                    @Html.Raw(page.Content)

                    <small class="fb-page-title">@page.Title</small>
                </div>
            </div>
        }
    </div>
    <!-- Search and Navigation Controls -->
    <div class="text-center mb-3">
        <input type="number" id="pageInput" placeholder="Enter page number" min="1" max="5" class="form-control form-control-sm" style="width: 200px; display: inline-block;">
        <button type="button" id="goToPageBtn" class="btn btn-sm btn-primary">Go</button>
    </div>


    <div class="text-center">
        <button type="button" id="playPauseBtn" class="btn btn-sm btn-success me-3"><i class="bi-volume-up"></i></button>
        <button type="button" id="prevBtn" class="btn btn-sm btn-secondary">Previous</button>
        <button type="button" id="nextBtn" class="btn btn-sm btn-secondary">Next</button>

        @if (Model.CountGrade == 0)
        {
            <a href="@Url.Action("Question", "Story", new { id = Model.ID })" class="btn btn-sm btn-warning ms-3">Take a Quiz</a>
        }
        else
        {
            <button type="button" class="btn btn-sm btn-warning ms-3" id="btnQuizResult">View Quiz Result</button>
        }
    </div>

</section><!-- /Stories Story Details Section -->


@section Scripts { 
    <script src="~/Scripts/tts.js"></script>

    <script>
         // Submit Answers:
        document.querySelector('#btnQuizResult').addEventListener('click', function () {
            $.ajax(
                {
                    type: "GET", //HTTP POST Method
                    url: "@Url.Action("ViewQuizResult", "Story")", // Controller/View
                    contentType: 'application/json; charset=utf-8',
                    data: { storyid: @ViewContext.RouteData.Values["id"] },
                    dataType: 'json',
                    beforeSend: function () {
                        Swal.showLoading();
                    },
                    success: function (result) {
                        console.log(result);
                        if (result != null) {
                            Swal.fire({
                                title: "Result",
                                icon: result.QuizAssessmentIcon,
                                html: `
                                    <div style="justify-content: center;display: flex;">
                                        <div role="progressbar" aria-valuenow="${result.QuizAssessmentPercentage}" aria-valuemin="0" aria-valuemax="100" style="--value: ${result.QuizAssessmentPercentage}"></div>
                                    </div>
                                    <p style="margin-top:1rem;">${result.QuizAssessmentMessage}</p>
                                  `
                            });
                        } else {
                            Swal.fire({
                                icon: "error",
                                title: "There was an error when retrieving your quiz result.",
                            });
                        }
                    }

                });
        });
       
    </script>


}